//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hikeforyourselfver3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hiking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hiking()
        {
            this.HikeRatings = new HashSet<HikeRating>();
            this.HikeBookings = new HashSet<HikeBooking>();
        }
    
        public int Id { get; set; }
        public string HikeName { get; set; }
        public string HikeLoc { get; set; }
        public string HikeDesc { get; set; }
        public string HikePrice { get; set; }
        public System.DateTime HikeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HikeRating> HikeRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HikeBooking> HikeBookings { get; set; }
    }
}
